# Generated by Django 5.2.8 on 2025-12-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commitment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='due_date',
        ),
    ]
