# Generated by Django 5.2.8 on 2026-01-07 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='invited_managers',
            field=models.ManyToManyField(blank=True, related_name='invited_commitments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commitment',
            name='is_sent_to_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('PS', 'Personal Secretary'), ('Manager', 'Manager'), ('HR', 'HR')], default='HR', max_length=30),
        ),
    ]
