# Generated by Django 5.2.8 on 2026-01-07 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commitment_invited_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='invited_managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'Manager'}, related_name='invited_commitments', to=settings.AUTH_USER_MODEL),
        ),
    ]
