# Generated by Django 5.2.8 on 2026-01-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_task_description_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='category',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Task', 'Task'), ('Visit', 'Visit'), ('Event', 'Event'), ('Urgent', 'Urgent'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
