# Generated by Django 5.2.8 on 2026-01-27 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_commitment_options_alter_remark_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={},
        ),
        migrations.RenameField(
            model_name='commitment',
            old_name='is_sent_to_manager',
            new_name='is_sent_to_subordinate',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='invited_managers',
        ),
        migrations.AddField(
            model_name='commitment',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_commitments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('GM', 'General Manager'), ('PS', 'Personal Secretary'), ('Manager', 'Manager'), ('Zonal Manager', 'Zonal Manager'), ('Assistant Manager', 'Assistant Manager'), ('HR', 'HR')], default='HR', max_length=30),
        ),
    ]
