# Generated by Django 5.2.8 on 2026-01-29 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_remark_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='commitment',
            old_name='is_sent_to_subordinate',
            new_name='is_sent_to_manager',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='invited_users',
        ),
        migrations.AddField(
            model_name='commitment',
            name='invited_managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'Manager'}, related_name='invited_commitments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('PS', 'Personal Secretary'), ('Manager', 'Manager'), ('HR', 'HR')], default='HR', max_length=30),
        ),
    ]
