# Generated by Django 5.2.8 on 2026-01-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_remark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('PS', 'Personal Secretary'), ('GM', 'General Manager'), ('Manager', 'Manager'), ('ZM', 'Zonal Manager'), ('AM', 'Assistant Manager'), ('HR', 'HR')], default='HR', max_length=30),
        ),
    ]
