# Generated by Django 5.2.8 on 2026-02-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='remark_attachments/'),
        ),
    ]
