# Generated by Django 5.2.8 on 2026-02-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remark_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'ordering': ['created_at']},
        ),
    ]
