# Generated by Django 5.2.8 on 2026-02-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_remark_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
