# Generated by Django 5.2.8 on 2026-02-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_task_is_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='attachment',
            new_name='attachment_1',
        ),
        migrations.AddField(
            model_name='remark',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='remark_attachments/'),
        ),
        migrations.AddField(
            model_name='remark',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to='remark_attachments/'),
        ),
    ]
