# Generated by Django 5.2.8 on 2026-02-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_attachment_remark_attachment_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_handler_role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('GM', 'General Manager'), ('CEO', 'CEO')], default='MANAGER', max_length=20),
        ),
    ]
