# Generated by Django 5.2.8 on 2026-02-24 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_task_current_handler_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='status_update',
        ),
        migrations.AddField(
            model_name='remark',
            name='action_taken',
            field=models.CharField(choices=[('save', 'Submitted'), ('forward', 'Forwarded to CEO'), ('reverse', 'Reversed to Manager'), ('approve', 'Final Approved')], default='save', max_length=20),
        ),
        migrations.AddField(
            model_name='remark',
            name='addressed_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='current_handler_role',
            field=models.CharField(default='Manager', max_length=50),
        ),
    ]
