# Generated by Django 5.2.8 on 2026-03-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_remark_action_taken_alter_task_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('current_handler_role', models.CharField(default='Manager', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notesheets_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notesheets_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notesheet',
                'verbose_name_plural': 'Notesheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotesheetAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='core.notesheet')),
            ],
            options={
                'verbose_name': 'Notesheet Agenda',
                'verbose_name_plural': 'Notesheet Agendas',
                'ordering': ['created_at'],
            },
        ),
    ]
