# Generated by Django 5.2.8 on 2026-03-03 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_notesheet_notesheetagenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notesheet',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notesheet',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='notesheet',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='notesheet',
            name='current_handler_role',
        ),
        migrations.AddField(
            model_name='notesheet',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_notesheets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notesheet',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notesheets_in_hand', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='NotesheetForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True)),
                ('forwarded_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notesheets_forwarded', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notesheets_received', to=settings.AUTH_USER_MODEL)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='core.notesheet')),
            ],
            options={
                'ordering': ['-forwarded_at'],
            },
        ),
    ]
