# Generated by Django 5.2.8 on 2026-03-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_notesheet_options_remove_notesheet_assigned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesheet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notesheetagenda',
            name='description',
        ),
    ]
