# Generated by Django 5.2.8 on 2026-03-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_notesheet_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheet',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notesheetforward',
            name='forwarded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
