# Generated by Django 5.2.8 on 2026-03-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_notesheet_due_date_alter_notesheet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheetforward',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notesheet_files/'),
        ),
    ]
