# Generated by Django 5.2.8 on 2026-03-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_notesheetforward_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesheetforward',
            name='attachment',
        ),
        migrations.AddField(
            model_name='notesheetforward',
            name='attachment_1',
            field=models.FileField(blank=True, null=True, upload_to='notesheet_forwards/'),
        ),
        migrations.AddField(
            model_name='notesheetforward',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='notesheet_forwards/'),
        ),
        migrations.AddField(
            model_name='notesheetforward',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to='notesheet_forwards/'),
        ),
    ]
