# Generated by Django 5.2.8 on 2026-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_file_notesheet_file_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
