# Generated by Django 5.2.8 on 2026-05-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_profile_role_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('PS', 'Personal Secretary'), ('GM', 'General Manager'), ('Manager', 'Manager'), ('ZM', 'Zonal Manager'), ('AM', 'Assistant Manager'), ('HR', 'HR')], default='HR', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DepartmentHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(help_text='e.g., Projects, Operations, Finance', max_length=100, unique=True)),
                ('manager_in_charge', models.ForeignKey(blank=True, help_text='Is department ka GM ya Head kaun hai (e.g., GM Operation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, help_text='Is GM ke under jitne bhi log aate hain (ZMs, AMs, Managers) un sab ko select karein', related_name='assigned_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Hierarchy',
                'verbose_name_plural': 'Department Hierarchies',
            },
        ),
    ]
