# Generated by Django 5.2.8 on 2026-05-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_profile_role_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentHierarchy',
        ),
    ]
