# Generated by Django 5.2.8 on 2026-05-20 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_delete_departmenthierarchy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.OneToOneField(help_text='Wo user jo boss hai (e.g., GM_Operation, CEO, AM)', on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_boss', to=settings.AUTH_USER_MODEL)),
                ('subordinates', models.ManyToManyField(blank=True, help_text='Is boss ke under jitne bhi log aate hain (e.g., Saare ZMs jo isko report karte hain)', related_name='hierarchy_subordinates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Hierarchy',
                'verbose_name_plural': 'User Hierarchies',
            },
        ),
    ]
