# Generated by Django 5.2.8 on 2026-05-21 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesheetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notesheet_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.notesheet')),
            ],
        ),
    ]
