# Generated by Django 5.2.8 on 2026-05-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_notesheetattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheet',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'Seen'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'Seen'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
