# Generated by Django 5.2.8 on 2026-06-01 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_notesheet_status_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheet',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'Seen'), ('Returned', 'Returned'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='NotesheetReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='notesheet_returns/')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='notesheet_returns/')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='notesheet_returns/')),
                ('returned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.notesheet')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notesheets_returned_by_me', to=settings.AUTH_USER_MODEL)),
                ('returned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notesheets_returned_to_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notesheet Return',
                'verbose_name_plural': 'Notesheet Returns',
                'ordering': ['-returned_at'],
            },
        ),
    ]
