# Generated by Django 5.2.8 on 2026-06-01 09:54

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_notesheet_status_notesheetreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheetagenda',
            name='agenda_title',
            field=tinymce.models.HTMLField(),
        ),
    ]
