# Generated by Django 5.2.8 on 2026-06-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_notesheetagenda_agenda_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheetattachment',
            name='flag_name',
            field=models.CharField(blank=True, help_text="e.g., 'A', 'B', 'C'", max_length=10, null=True),
        ),
    ]
