# Generated by Django 5.2.8 on 2026-07-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('commitment_created', 'New Commitment'), ('commitment_approved', 'Commitment Approved'), ('commitment_rejected', 'Commitment Rejected'), ('task_assigned', 'Task Assigned'), ('commitment_invite', 'Invited to Commitment')], max_length=40),
        ),
    ]
