# Generated by Django 5.2.8 on 2026-07-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('commitment_created', 'New Commitment'), ('commitment_approved', 'Commitment Approved'), ('commitment_rejected', 'Commitment Rejected'), ('task_assigned', 'Task Assigned')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('PS', 'Personal Secretary'), ('GM', 'General Manager'), ('Manager', 'Manager'), ('ZM', 'Zonal Manager'), ('AM', 'Assistant Manager'), ('HR', 'HR'), ('IT', 'Officer'), ('CFO', 'Chief Financial Officer')], default='HR', max_length=30),
        ),
    ]
