# Generated by Django 5.2.8 on 2026-07-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='category',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Visit', 'Visit'), ('Event', 'Event')], default='Meeting', max_length=50),
        ),
    ]
