# Generated by Django 5.2.8 on 2026-07-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_commitment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=20),
        ),
    ]
