# Generated by Django 5.2.8 on 2026-07-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_letterfile_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='cc_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='recipient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='signer_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='signer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
