# Generated by Django 5.2.8 on 2026-07-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_letter_cc_list_letter_recipient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
