# Generated by Django 5.2.8 on 2026-07-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_profile_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('commitment_created', 'New Commitment'), ('commitment_approved', 'Commitment Approved'), ('commitment_rejected', 'Commitment Rejected'), ('task_assigned', 'Task Assigned'), ('task_feedback', 'Task Feedback Added')], max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Seen', 'Seen'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
