# Generated by Django 5.2.8 on 2026-08-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_notification_notif_type_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='reply_attachment',
            field=models.FileField(blank=True, null=True, upload_to='letter_replies/'),
        ),
        migrations.AddField(
            model_name='letter',
            name='reply_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
