# Generated by Django 5.2.8 on 2026-08-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_letter_reply_attachment_letter_reply_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='remark_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.remark')),
            ],
        ),
    ]
