# Generated by Django 5.2.8 on 2026-08-03 09:42

from django.db import migrations


def migrate_attachments(apps, schema_editor):
    Remark = apps.get_model('core', 'Remark')
    RemarkAttachment = apps.get_model('core', 'RemarkAttachment')
    for remark in Remark.objects.all():
        for field in ('attachment_1', 'attachment_2', 'attachment_3'):
            file_val = getattr(remark, field)
            if file_val:
                RemarkAttachment.objects.create(remark=remark, file=file_val)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remarkattachment'),
    ]

    operations = [
        migrations.RunPython(migrate_attachments),
    ]
