# Generated by Django 5.2.8 on 2026-08-03 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_migrate_old_remark_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterReplyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='letter_reply_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_attachments', to='core.letter')),
            ],
        ),
    ]
