# Generated by Django 5.2.8 on 2026-08-03 10:31

from django.db import migrations


def migrate_reply_attachments(apps, schema_editor):
    Letter = apps.get_model('core', 'Letter')
    LetterReplyAttachment = apps.get_model('core', 'LetterReplyAttachment')
    for letter in Letter.objects.all():
        if letter.reply_attachment:
            LetterReplyAttachment.objects.create(letter=letter, file=letter.reply_attachment)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_letterreplyattachment'),
    ]

    operations = [
        migrations.RunPython(migrate_reply_attachments),
    ]
