# Generated by Django 5.2.8 on 2026-08-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_migrate_old_letter_reply_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
