# Generated by Django 5.2.8 on 2026-08-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_letter_is_draft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
