# Generated by Django 5.2.8 on 2026-08-25 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftLetter',
            fields=[
            ],
            options={
                'verbose_name': 'Draft Letter',
                'verbose_name_plural': 'Draft Letters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.letter',),
        ),
        migrations.CreateModel(
            name='VehicleRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fleet_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions_created', to=settings.AUTH_USER_MODEL)),
                ('manager_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
