# Generated by Django 5.2.8 on 2026-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_draftletter_vehiclerequisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequisition',
            name='driver_cnic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerequisition',
            name='driver_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerequisition',
            name='estimated_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerequisition',
            name='previous_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerequisition',
            name='uc_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerequisition',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
