# Generated by Django 5.2.8 on 2026-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_vehiclerequisition_driver_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequisition',
            name='driver_signature',
            field=models.ImageField(blank=True, null=True, upload_to='requisition_signatures/'),
        ),
        migrations.AddField(
            model_name='vehiclerequisition',
            name='fleet_officer_signature',
            field=models.ImageField(blank=True, null=True, upload_to='requisition_signatures/'),
        ),
    ]
