# Generated by Django 5.2.8 on 2026-08-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_logbook_logbookentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbookentry',
            name='logbook',
        ),
        migrations.DeleteModel(
            name='LogBook',
        ),
        migrations.DeleteModel(
            name='LogBookEntry',
        ),
    ]
