# Generated by Django 5.2.8 on 2026-09-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_logbookentry_logbook_delete_logbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('PS', 'Personal Secretary'), ('GM', 'General Manager'), ('Manager', 'Manager'), ('ZM', 'Zonal Manager'), ('AM', 'Assistant Manager'), ('HR', 'HR'), ('IT', 'Officer'), ('CFO', 'Chief Financial Officer'), ('Auditor', 'Auditor')], default='HR', max_length=30),
        ),
    ]
