# Generated by Django 5.2.8 on 2026-09-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
