# Generated by Django 5.2.8 on 2026-09-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_profile_employee_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role / Designation Name (e.g. General Manager - HR)', max_length=150)),
                ('code', models.CharField(help_text='Unique Role Code (e.g. CEO, PS, GM_HR, MNGR_FIN)', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('CEO', 'CEO'), ('PS', 'Personal Secretary'), ('GM', 'General Manager'), ('Manager', 'Manager'), ('ZM', 'Zonal Manager'), ('AM', 'Assistant Manager'), ('HR', 'HR'), ('Officer', 'Officer'), ('CFO', 'Chief Financial Officer'), ('Auditor', 'Auditor'), ('Other', 'Other')], default='Manager', help_text='Base Role Category for Permissions & Dashboards', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
