# Generated by Django 5.2.8 on 2026-09-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.AlterField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('CEO', 'CEO'), ('PS', 'Personal Secretary'), ('GM', 'General Manager'), ('Manager', 'Manager'), ('ZM', 'Zonal Manager'), ('AM', 'Assistant Manager'), ('HR', 'HR'), ('Officer', 'Officer'), ('CFO', 'Chief Financial Officer'), ('Auditor', 'Auditor'), ('Other', 'Other')], default='Manager', help_text='Base Role Category for Permissions & Dashboards', max_length=50, verbose_name='Base Role Category'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(help_text='e.g. GM-PMER, GM-HR, MngrBilling', max_length=50, unique=True, verbose_name='Role Code / Short Title'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Full Designation (e.g. General Manager, Manager)', max_length=150, verbose_name='Full Role Name'),
        ),
    ]
