# Generated by Django 5.2.8 on 2026-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_role_category_alter_role_code_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Full Name'),
        ),
    ]
