# Generated by Django 5.2.8 on 2026-09-08 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_role_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequisition',
            name='is_first_time',
            field=models.BooleanField(default=False, verbose_name='First time occurrence'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='invited_managers',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('profile__role__category', 'Manager'), ('profile__role__code', 'Manager'), _connector='OR'), related_name='invited_commitments', to=settings.AUTH_USER_MODEL),
        ),
    ]
