# Generated by Django 5.2.8 on 2026-09-08 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_vehiclerequisition_is_first_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Head Office, Zone-A, Zone-B', max_length=100, unique=True)),
                ('title', models.CharField(default='WATER AND SANITATION SERVICES PESHAWAR', help_text='Main title on letterhead', max_length=200)),
                ('subtitle', models.CharField(default='LOCAL GOVERNMENT COMPLEX, KHYBER PAKHTUNKHWA.', help_text='Subtitle on letterhead', max_length=255)),
                ('address', models.CharField(default='Plot # 33, Street No. 13, Sector E-8, Phase-VII, Hayatabad', help_text='Address on letterhead', max_length=255)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.zone'),
        ),
    ]
