# Generated by Django 5.2.8 on 2026-09-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_zone_profile_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='logo_left',
            field=models.ImageField(blank=True, help_text='Left logo (defaults to WSSP logo if empty)', null=True, upload_to='zone_logos/'),
        ),
        migrations.AddField(
            model_name='zone',
            name='logo_right',
            field=models.ImageField(blank=True, help_text='Right logo (defaults to KPK Emblem if empty)', null=True, upload_to='zone_logos/'),
        ),
        migrations.AddField(
            model_name='zone',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for the letterhead', max_length=100, null=True),
        ),
    ]
