# Generated by Django 5.2.8 on 2026-09-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_zone_logo_left_zone_logo_right_zone_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='province',
            field=models.CharField(blank=True, default='GOVERNMENT OF KHYBER PAKHTUNKHWA', help_text='Province line on letterhead (e.g., Government of Khyber Pakhtunkhwa)', max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='address',
            field=models.CharField(blank=True, default='Plot # 33, Street No. 13, Sector E-8, Phase-VII, Hayatabad', help_text='Address on letterhead', max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='subtitle',
            field=models.CharField(default='WATER AND SANITATION SERVICES PESHAWAR', help_text='Subtitle on letterhead (2nd line)', max_length=255),
        ),
    ]
