# Generated by Django 5.2.8 on 2026-09-11 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_zone_province_alter_zone_address_alter_zone_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRequisitionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requisition_attachments/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.vehiclerequisition')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
