# Generated by Django 5.2.8 on 2026-09-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_add_vehicle_requisition_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRequisitionForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True)),
                ('forwarded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('forwarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqs_forwarded', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqs_received_forwards', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='core.vehiclerequisition')),
            ],
            options={
                'ordering': ['-forwarded_at'],
            },
        ),
    ]
