# Generated by Django 5.2.8 on 2026-09-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_vehiclerequisitionforward'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequisitionforward',
            name='status_at_forward',
            field=models.CharField(blank=True, default='Pending', max_length=20),
        ),
    ]
