# Generated by Django 5.2.8 on 2026-09-17 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_vehiclerequisitionforward_status_at_forward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userhierarchy',
            name='document_type',
            field=models.CharField(choices=[('All', 'All Documents'), ('Task', 'Task'), ('Letter', 'Letter'), ('Notesheet', 'Notesheet'), ('Requisition', 'Requisition Form')], default='All', help_text='Select which document type this hierarchy applies to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='boss',
            field=models.ForeignKey(help_text='Wo user jo boss hai (e.g., GM_Operation, CEO, AM)', on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_bosses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userhierarchy',
            unique_together={('boss', 'document_type')},
        ),
    ]
