# Generated by Django 5.2.8 on 2026-09-17 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_userhierarchy_document_type_alter_userhierarchy_boss_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userhierarchy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userhierarchy',
            name='all_subs',
            field=models.ManyToManyField(blank=True, related_name='all_bosses', to=settings.AUTH_USER_MODEL, verbose_name='Default (All Documents) List'),
        ),
        migrations.AddField(
            model_name='userhierarchy',
            name='letter_subs',
            field=models.ManyToManyField(blank=True, related_name='letter_bosses', to=settings.AUTH_USER_MODEL, verbose_name='Letter List'),
        ),
        migrations.AddField(
            model_name='userhierarchy',
            name='notesheet_subs',
            field=models.ManyToManyField(blank=True, related_name='notesheet_bosses', to=settings.AUTH_USER_MODEL, verbose_name='Notesheet List'),
        ),
        migrations.AddField(
            model_name='userhierarchy',
            name='requisition_subs',
            field=models.ManyToManyField(blank=True, related_name='req_bosses', to=settings.AUTH_USER_MODEL, verbose_name='Requisition Form List'),
        ),
        migrations.AddField(
            model_name='userhierarchy',
            name='task_subs',
            field=models.ManyToManyField(blank=True, related_name='task_bosses', to=settings.AUTH_USER_MODEL, verbose_name='Task List'),
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='boss',
            field=models.OneToOneField(help_text='Wo user jo boss hai (e.g., fozoned, gm-ops, ceo)', on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_boss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='subordinates',
        ),
    ]
