# Generated by Django 5.2.8 on 2026-09-17 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_userhierarchy_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhierarchy',
            name='all_subs',
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='boss',
            field=models.OneToOneField(help_text='Select the user for whom you are configuring the forwarding lists.', on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_boss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
