# Generated by Django 5.2.8 on 2026-08-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_vehicle_alter_logbook_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbookentry',
            old_name='signature',
            new_name='driver_signature',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_cnic',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_mobile',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='logbook',
            name='average_to_litre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average KM per litre', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='fleet_officer_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
