# Generated by Django 5.2.8 on 2026-09-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_rename_signature_logbookentry_driver_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='FuelRecord',
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
    ]
