# Generated by Django 5.2.8 on 2026-09-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_logbookentry_logbook_delete_logbook_and_more'),
        ('logbook', '0004_remove_maintenancerecord_vehicle_delete_fuelrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookentry',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbook_entries', to='core.vehiclerequisition'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='signed_requisition',
            field=models.FileField(blank=True, null=True, upload_to='signed_requisitions/'),
        ),
    ]
