# Generated by Django 5.2.8 on 2026-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_logbookentry_requisition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookentry',
            name='record_type',
            field=models.CharField(blank=True, choices=[('Journey', 'Journey'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], default='Journey', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Tyre Replacement', 'Tyre Replacement'), ('Oil Change', 'Oil Change'), ('Battery Replacement', 'Battery Replacement'), ('General Service', 'General Service'), ('Repair', 'Repair'), ('Inspection', 'Inspection'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
