# Generated by Django 5.2.8 on 2026-09-02 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_logbookentry_record_type_logbookentry_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='logbook.logbook')),
            ],
            options={
                'verbose_name': 'Log Book Page',
                'verbose_name_plural': 'Log Book Pages',
                'ordering': ['page_number'],
                'unique_together': {('logbook', 'page_number')},
            },
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='logbook.logbookpage'),
        ),
    ]
