# Generated by Django 5.2.8 on 2026-09-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_logbookpage_logbookentry_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='details_of_journey',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='meter_reading_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='meter_reading_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='officer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='purpose_of_journey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='signed_requisition',
            field=models.FileField(blank=True, null=True, upload_to='signed_requisitions/', verbose_name='Image Upload'),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
