# Generated by Django 5.2.8 on 2026-09-03 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_alter_logbookentry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='signed_requisition',
            field=models.FileField(blank=True, null=True, upload_to='signed_requisitions/', verbose_name='Upload Document / File (PDF / Image)'),
        ),
    ]
