# Generated by Django 5.2.8 on 2026-09-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0011_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookpage',
            name='pdf_page_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
