# Generated by Django 5.2.8 on 2026-09-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_zone_logo_left_zone_logo_right_zone_phone'),
        ('logbook', '0012_logbookpage_pdf_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zone this vehicle belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.zone'),
        ),
    ]
