# Generated by Django 5.2.8 on 2026-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0013_alter_vehicle_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbook',
            options={'ordering': ['vehicle_name'], 'verbose_name': 'Log Book', 'verbose_name_plural': 'Log Books'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['vehicle_name'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='vehicle_number',
            new_name='vehicle_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_meter_reading',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(default='Unknown', help_text='Name/identifier of the vehicle', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
