# Generated by Django 5.2.8 on 2026-09-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0014_alter_logbook_options_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30),
        ),
    ]
